openfheorg/openfhe-development

src/binfhe/include/binfhecontext.h, src/binfhe/lib/binfhecontext.cpp, src/binfhe/lib/lwe.cpp
Unoptimized boolean circuits sometimes need access to embeddings of constant values. Since they are constant, no encryption/noise is required.
(Also, this somehow got partially dropped in moving from PALISADE to OpenFHE.)
=> Restore EvalConstant for BinFHE

src/binfhe/include/binfhecontext.h
m_timeOptimization is not initialized on all paths, so risks uninitialized memory problems unless initialized by default.
=> Fix uninitialized memory issues

src/pke/include/scheme/bgvrns/bgvrns-leveledshe.h, src/pke/include/scheme/ckksrns/ckksrns-leveledshe.h, src/pke/include/schemebase/base-leveledshe.h, src/pke/include/schemebase/base-scheme.h, src/pke/include/schemerns/rns-leveledshe.h, src/pke/lib/scheme/bgvrns/bgvrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/lib/schemebase/base-leveledshe.cpp, src/pke/lib/schemerns/rns-leveledshe.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
closes #59 
Added MorphPlaintext method that creates a ciphertext with a single element from a plaintext.
In UnitTests changed MakeCKKSPackedPlaintext depth from 3 to 2 (to be compatible with AUTO logic, where depth <= 2)
In UnitTests changed eps -> epsHigh where FIXEDAUTO mode precision become worse.
=> operations with plaintexts without decoding and encoding again

benchmark/src/mult-vs-square.cpp, src/pke/include/cryptocontext.h, src/pke/include/scheme/bfvrns/bfvrns-leveledshe.h, src/pke/include/scheme/bgvrns/bgvrns-leveledshe.h, src/pke/include/scheme/ckksrns/ckksrns-leveledshe.h, src/pke/include/schemebase/base-leveledshe.h, src/pke/include/schemebase/base-scheme.h, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/bgvrns/bgvrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/lib/schemebase/base-leveledshe.cpp
1) Added Leveled Hybrid Key Switching:
Now in HPSPOVERQLEVELED we also drop levels at KeySwitch step. 
2) Added EvalSquare
Added implementation of EvalSquare for BFV scheme. Previously EvalSquare was working only for CKKS and BGV scheme
Added benchmark mult-vs-square which evaluates Enc(x^{2^k}) using EvalMult and EvalSquare. 
EvalSquare is 10-20% faster.
3) Refactored Rotation indexes
change check (cc->getSchemeId() == "CKKSRNS") from base-leveledshe.cpp in Automorphism methods and instead added FindAutomorphismIndex method for each scheme.
=> 113 bfv keyswitch

src/pke/lib/schemebase/base-advancedshe.cpp
Adds tracking the number of slots in a ciphertext for some operations. Needed for the genomic examples.
=> Fixes related to tracking the number of slots for CKKS

src/pke/examples/README.md, src/pke/include/scheme/cryptocontextparams-base.h, src/pke/include/schemebase/base-cryptoparameters.h, src/pke/include/schemebase/rlwe-cryptoparameters.h
1. Added cryptoparameter descriptions and instructions how to build user applications to src/pke/examples/README.md
2. Corrected some comments and changed the type of maxRelinSkDegi from int to uint32_t (see src/pke/include/scheme/cryptocontextparams-base.h)
=> Document cryptocontext parameters

src/core/include/lattice/hal/dcrtpoly-interface.h, src/core/include/lattice/hal/default/dcrtpoly.h, src/core/lib/lattice/hal/default/dcrtpoly.cpp, src/pke/include/schemerns/rns-cryptoparameters.h
This branch fixes this [issue](https://github.com/openfheorg/openfhe-development/issues/250).
In short, it removes assumptions that mTilde and related params are of type uint16_t.
=> Switch mTilde related params to uint64_t

src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/unittest/utckksrns/UnitTestBootstrap.cpp
This resolves Issue #305 and Issues #229. If we input a ciphertext with towers > # towers we end up with after bootstrapping, we return the original ciphertext. We exhibit this behavior for both single and double-iteration bootstrapping.
=> Return original ciphertext in bootstrapping if we already start with enough towers.

src/pke/include/cryptocontext.h
Throwing exception when vector of values is empty in packedencoding. Some spacing changes caused by pre-commit
=> minor bug fix for issue 306

src/core/lib/math/nbtheory.cpp
This change should resolve this [issue](https://openfhe.discourse.group/t/setting-security-parameters-according-to-128-bit-security-very-small-ckks-scaling-factor/396) on OpenFHE discourse. 
Tha main reason for this issue is that setting the moduli size to a small value might cause an overflow in the moduli generation logic.
=> add check to prevent negative moduli

src/binfhe/examples/eval-decomp.cpp, src/binfhe/lib/binfhe-base-scheme.cpp, src/binfhe/unittest/UnitTestFunc.cpp
@RaindropFamily: The eval-decomp example in binfhe was giving the wrong output (for the last digit). It doesn't look like the final bootstrapping in the eval-decomp function is needed (the algorithm in the paper doesn't have it either). Removing the final bootstrapping in evaldecomp function and changing p=8 from p =2 in decrypt for the last digit in the example fixes the issue. Can you review the changes?
=> Fix eval-decomp example returning wrong output

src/core/include/math/hal/intnat/transformnat-impl.h
fix for 5x slowdown of native forward ntt when compiled with clang and NATIVE_OPT=OFF. Fix only applied to transform used in SwitchFormat().
https://docs.google.com/spreadsheets/d/1iO8RK2bDOfCZTkfClyt1BYFUBtUyPDfLYmXqfc8ErgU/edit?usp=sharing
=> Modified Native Transform

src/pke/examples/inner-product.cpp, src/pke/unittest/utbfvrns/UnitTestBFVrnsInnerProduct.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrnsInnerProduct.cpp
Test failing on BFV. Not failing on CKKS? But commenting out all anyways
=> Comment out EvalInnerProductX tests temporarily

src/pke/lib/encoding/ckkspackedencoding.cpp, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
The maximum word size supported by 64-bit numbers was set incorrectly.
Unit tests were added to test this scenario.
=> fixed the bug with large CKKS plaintexts

src/binfhe/lib/binfhecontext.cpp
Generated Q the correct way, using the cyclotomic order (2 * ring dimension) instead of ring dimension. The generated Q has the same value as before, since it happened to already satisfy the condition 1 mod 2 * ring dimension for the two options dictated by logQprime.
Also changed a comment to match the code.
=> Fixed modulus computation in GenerateBinFHEContext overload (issue#426)

src/pke/lib/encoding/ckkspackedencoding.cpp, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp
Patch out two instances of casting a potentially-infinite floating point value to int32_t. (The other issue from PR#415 has already been fixed in dev.)
=> Port of PR#415 - Fix some undefined behavior

src/pke/include/cryptocontext.h
Limited the upper value of the level to encode the plaintext at.
=> Fix for segmentation fault in MakeCKKSPackedPlaintext()

src/pke/include/constants.h, src/pke/lib/encoding/ckkspackedencoding.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
Fixes #385 and #393 
* Fixes the logic for adding large doubles in CKKS
* Fixes the logic for multiplying by large doubles in CKKS
* Adds unit tests for addling large doubles
=> Fixes bugs with large scalars in CKKS

src/binfhe/include/binfhecontext.h, src/binfhe/include/rgsw-acc-lmkcdey.h, src/binfhe/include/rgsw-cryptoparameters.h, src/binfhe/lib/binfhecontext.cpp, src/binfhe/lib/rgsw-acc-lmkcdey.cpp
This PR introduces parameterization for the number of automorphism keys in the LMKCDEY bootstrapping. 
The formerly hardcoded value of `m_window = 10` has been updated and is now integrated into `RingGSWCryptoParams` under the variable name `numAutoKeys`.
=> Add numAutoKeys to RingGSWCryptoParams

src/core/include/math/hal/intnat/ubintnat.h, src/pke/include/scheme/bfvrns/bfvrns-leveledshe.h, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/bfvrns/bfvrns-multiparty.cpp, src/pke/lib/scheme/bfvrns/bfvrns-pke.cpp, src/pke/unittest/UnitTestSHE.cpp
As part of the change, rewrote MultiplyAndRound for the native backend. This method is now used for BFV decryption for a DCRTPoly with a single RNS limb.
=> added support for Compress to BFV for HPS* modes

src/binfhe/examples/boolean-multi-input.cpp, src/binfhe/include/binfhe-base-scheme.h, src/binfhe/include/binfhe-constants.h, src/binfhe/include/binfhecontext.h, src/binfhe/include/lwe-ciphertext.h, src/binfhe/lib/binfhe-base-scheme.cpp, src/binfhe/lib/binfhe-constants-impl.cpp, src/binfhe/lib/binfhecontext.cpp, src/binfhe/lib/lwe-pke.cpp, src/binfhe/lib/rgsw-cryptoparameters.cpp, src/binfhe/unittest/UnitTestFHEW.cpp
duplicate of PR #480 with new branch
* Updated AND3, OR3, MAJORITY, CMUX gates for 3 inputs and AND4, OR4 for 4 inputs. CMUX is implemented with 3 NAND operations (3 bootstrappings).
* Added unit tests for the gates in UnitTestFHEW
* Added example boolean-multi-input
=> Code for multi-input gates

src/pke/include/README.md, src/pke/include/scheme/ckksrns/ckksrns-fhe.h, src/pke/lib/scheme/bfvrns/bfvrns-multiparty.cpp, src/pke/lib/scheme/bfvrns/bfvrns-pke.cpp, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/lib/schemebase/base-multiparty.cpp, src/pke/lib/schemebase/base-pke.cpp
1. Increased the Hamming weight from 64 to 192.
2. Switched from Chebyshev approximation to Chebyshev approximation + double-angle formula.
=> Hardening and optimizations of CKKS bootstrapping for sparse secret distribution

src/binfhe/lib/rgsw-acc-cggi.cpp, src/binfhe/lib/rgsw-acc-dm.cpp, src/binfhe/lib/rgsw-acc-lmkcdey.cpp, src/binfhe/lib/rgsw-acc.cpp
* Re-implemented the changes in PR #482 as the binfhe code has significantly changed as compared to the commit the branch was created from (it was easier to reimplement than resolve the conflicts)
* Optimized the `Automorphism` bootstrapping step for the LMKCDEY mode
* Removed 2 NTTs (automorphisms can be done directly in EVALUATION representation)
* Switched to an optimized version of automorphisms (with precomputed bit reversal tables)
Ran benchmarks for STD128* on an Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz and 64 GB of RAM, running Ubuntu 20.04 LTS with clang 10.0.0 (CMake flags: NATIVE_SIZE=32; WITH_NATIVEOPT=ON; OMP_NUM_THREADS=1)
* GINX (TFHE) runtime went down from 49 ms to 39 ms.
* LMKCDEY (FHEW) runtime went down from 40 ms to 29 ms.
=> implemented approximate gadget decomposition + optimization for LMKCDEY

src/pke/lib/scheme/ckksrns/ckksrns-schemeswitching.cpp
The encoding for complex numbers in scheme switching has now the patches for avoiding overflow from ckksrns-fhe.
=> patched encoding

src/pke/include/cryptocontext.h, src/pke/include/schemebase/base-advancedshe.h, src/pke/include/schemebase/base-leveledshe.h, src/pke/include/schemebase/base-scheme.h, src/pke/lib/cryptocontext.cpp, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-schemeswitching.cpp, src/pke/lib/schemebase/base-advancedshe.cpp, src/pke/lib/schemebase/base-leveledshe.cpp, src/pke/lib/schemebase/base-scheme.cpp, src/pke/unittest/utils/UnitTestSer.h
This reverts commit 01222388e9b28f002d93e87d28c867e990616421.
=> Revert "Create one map for all automorphism keys (#566)"

src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-utils.cpp, src/pke/unittest/utckksrns/UnitTestBootstrap.cpp
=> boot for single slot

src/pke/include/scheme/bfvrns/gen-cryptocontext-bfvrns-internal.h, src/pke/include/schemerns/rns-parametergeneration.h
1. Now uses the scaling mod size instead of first mod size for setting the size of RNS moduli in BFV
2. Reduces the MIN_SIZE from 30 to 14
Closes #619 and #555
=> Fixes a bug in the interface for BFV generation

src/pke/examples/iterative-ckks-bootstrapping.cpp, src/pke/examples/simple-ckks-bootstrapping.cpp, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp
* Updated `GetBootstrapDepth` to use the correct number of levels (was 1 lower)
* Updated the bootstrapping examples to show the correct number of remaining levels after bootstrapping
=> Fixed GetBootstrapDepth

src/core/include/math/hal/bigintntl/ubintntl.h, src/core/include/math/hal/intnat/ubintnat.h, src/pke/lib/scheme/bfvrns/bfvrns-cryptoparameters.cpp, src/pke/lib/scheme/bgvrns/bgvrns-cryptoparameters.cpp, src/pke/lib/scheme/ckksrns/ckksrns-cryptoparameters.cpp, src/pke/lib/scheme/ckksrns/ckksrns-multiparty.cpp, src/pke/lib/schemerns/rns-cryptoparameters.cpp
cherry picked commits from https://github.com/openfheorg/openfhe-development/pull/624 and https://github.com/openfheorg/openfhe-development/pull/579 with some cleanup
=> Powerpc s390 support

benchmark/src/lib-benchmark.cpp, benchmark/src/poly-benchmark.h, src/core/include/lattice/hal/dcrtpoly-interface.h, src/core/include/lattice/hal/default/dcrtpoly-impl.h, src/core/include/lattice/hal/default/dcrtpoly.h, src/core/include/lattice/ilelement.h, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/unittest/utbfvrns/UnitTestBFVrnsCRTOperations.cpp
- Fix for slowdown at large number of threads
- Fix for lazy reduction issues for some methods in DCRTPoly
- Remove at() and [] access operators from DCRTPoly
- Removal of some unnecessary DCRTPoly copies
- Force DCRTPoly::CRTInterpoate() to only use COEFFICIENT format
- Remove Precon variables from DropLastElementAndScale
- Updates to lib-benchmark poly-benchmark
=> Fix for slowdown at a large number of threads

src/core/include/utils/exception.h
Shows more information when an exception is throw, including the file and line where it is thrown.
=> Return m_errorMessage instead of m_errorDescription from what() in OpenFHEException

src/pke/examples/scheme-switching.cpp, src/pke/lib/scheme/ckksrns/ckksrns-schemeswitching.cpp
In https://github.com/openfheorg/openfhe-development/pull/665 numCtxts was used before its value (default= 0) was checked. This was causing a segfault in some scheme-switching examples which didn't specify numCtxts.
Closes #711.
=> Moved check on optional argument before it is used in EvalCKKStoFHEW

src/pke/examples/simple-integers.cpp, src/pke/include/cryptocontext.h, src/pke/include/schemerns/rns-cryptoparameters.h, src/pke/lib/scheme/bfvrns/bfvrns-cryptoparameters.cpp, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/bfvrns/bfvrns-multiparty.cpp, src/pke/lib/scheme/bfvrns/bfvrns-pke.cpp, src/pke/unittest/UnitTestSHE.cpp, src/pke/unittest/utbfvrns/UnitTestBFVrns.cpp
High-level summary: 
- All operations on compressed ciphertexts are supported for HPSPOVERQ and HPSOVERQLEVELED. 
- As soon as a ciphertext is compressed, HPSOVERQLEVELED switches to HPSPOVERQ (to avoid correctness issues due to two competing mechanisms for compressing ciphertexts). When ciphertexts are not compressed, HPSOVERQLEVELED operates the same way as before.
- Compress and encode at level > 0 throw exceptions for BEHZ, HPS; and EXTENDED encryption. 
- I did not add any special logic for ciphertexts/plaintexts with mismatched levels (it can actually be somewhat tricky as the message lives in MSD); so the existing (lower-level) exceptions are thrown. 
- This BFV mode is currently only for FHE experts or compilers. We can make it more usable later (when we add noise estimation).
- …
=> Added support for modulus switching to BFV

src/pke/include/schemebase/base-leveledshe.h, src/pke/lib/scheme/ckksrns/ckksrns-schemeswitching.cpp, src/pke/lib/schemebase/base-leveledshe.cpp
- Added checks on the number of limbs in the core functions with two inputs (at deepest level).  @dsuponitskiy
- Fixed a plaintext generation with extra limbs which was throwing an exception.
Closes #721.
=> 721 add exceptions

src/pke/lib/scheme/ckksrns/ckksrns-cryptoparameters.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
The wrong scaling factor was used for FLEXIBLEAUTO* modes at multiplicative depth = 0. It was using the first modulus size instead of the scaling factor. Now it is corrected.
=> fixed a bug with mult depth = 0 for CKKS FLEXIBLEAUTO* modes

src/pke/lib/scheme/ckksrns/ckksrns-advancedshe.cpp
Fixed bug in polynomial evaluation for degree >= 5 by replacing some assignment operators by cloning operators.
A separate [issue](https://github.com/openfheorg/openfhe-development/issues/771) will take care of streamlining the code.
Closes https://github.com/openfheorg/openfhe-development/issues/769.
=> 769 fix bug in evalchebyshevseriesps

src/pke/include/scheme/bgvrns/bgvrns-parametergeneration.h, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/bfvrns/bfvrns-parametergeneration.cpp, src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp
Refines BGV and BFV key switching estimates to correspond to Appendix B of https://eprint.iacr.org/2021/204
=> Minor noise estimation fixes for BGV and BFV

src/pke/include/schemerns/rns-cryptoparameters.h, src/pke/lib/scheme/bfvrns/bfvrns-parametergeneration.cpp, src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp, src/pke/lib/scheme/ckksrns/ckksrns-parametergeneration.cpp, src/pke/lib/schemerns/rns-cryptoparameters.cpp, src/pke/unittest/UnitTestCoexistingCryptocontexts.cpp
1. Added EstimateLogP and EstimateMultipartyFloodingLogQ
2. Updated the logic for BGV, BFV, and CKKS to use these methods prior to checking (finding) the ring dimension based on the LWE security tables
=> Fix logQ(P) estimation used for finding the minimum ring dimension

benchmark/src/binfhe-paramsets.cpp, src/binfhe/examples/boolean-multi-input.cpp, src/binfhe/include/binfhe-constants.h, src/binfhe/include/binfhecontext.h, src/binfhe/include/rgsw-cryptoparameters.h, src/binfhe/lib/binfhe-constants-impl.cpp, src/binfhe/lib/binfhecontext.cpp
- modified default LMKCDEY param sets to lower expected probability of failure (2**-20 --> 2**-40)
- added LPF-qualified BINFHE_PARAMSETs for STD128 and STD128Q with very low probability of failure (e.g., 2**-120 for LPF_STD128)
- added approximate probability of failure to BINFHE_PARAMSET descriptions
- added binfhe-paramsets benchmark
- fixed small bug in rgsw-cryptoparameters.h
- changed data type for N in GenerateBinFHEContext() from innt64_t to uint32_t
- cleaned up binfhecontext.cpp
- modified implementation for BinFHEContext::GenerateLUTviaFunction()
=> 778 fix lmkcdey parameter sets

src/pke/lib/schemebase/base-leveledshe.cpp
Fixed some errors to enable OMP in EvalAutomorphismKeyGen()
=> Enable omp in evalautomorphism

src/pke/lib/scheme/ckksrns/ckksrns-parametergeneration.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
1. Make sure that the vector of moduliQ in ParamsGenCKKSRNS() has no duplicate values.
2. Push error handling to the top of the function
3. Reorganize code and replace usint with uint32_t
4. Add unit tests
=> No repeated primes in the limb moduli for CKKS

CMakeLists.txt, src/binfhe/lib/binfhe-base-scheme.cpp, src/core/include/math/hal/intnat/ubintnat.h, src/pke/unittest/utbgvrns/UnitTestBGVrnsAdvancedSHE.cpp
[fix for -Wshift-op-parentheses warning in ubintnat.h](https://github.com/openfheorg/openfhe-development/issues/823)
=> clang-specific compiler warnings

src/pke/examples/README.md, src/pke/lib/scheme/gen-cryptocontext-params-validation.cpp
* do not allow ringDim = 0 for NOISE_FLOODING_HRA
* SetFirstModSize and SetScaleModSize should be disabled for NOISE_FLOODING_HRA
=> Additional parameter validations for BGV

src/pke/include/cryptocontext.h
Fix: deserialize the keys and add them to the existing static map with EvalMultKeys providing the correct tag
=> Fixed DeserializeEvalMultKey() as it overwrites keymap content

src/pke/lib/encoding/ckkspackedencoding.cpp
Removes the integer values of polynomials so that the user could only access the floating-point values
=> Clear polynomials during CKKS decryption

src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp
In the SlotsToCoefficients implementation via collapsed FFT, when the levels cannot be collapsed exactly in the given budget, there were some extra rotation keys being generated. Those extra keys are now removed.
=> Remove the extra keys in homomorphic decode

src/pke/include/schemerns/rns-cryptoparameters.h, src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp, src/pke/lib/scheme/ckksrns/ckksrns-parametergeneration.cpp, src/pke/lib/schemerns/rns-cryptoparameters.cpp
1. Incremented the estimated modulus for BGV and CKKS by 1 to account for RNS moduli above the desired bit width
2. Incremented the maximum digit size in hybrid key switching for BGV and CKKS by 1 to account for RNS moduli above the desired bit width
=> Fixed the estimation logic for hybrid key switching

src/core/include/math/hal/intnat/transformnat-impl.h
5% - 9% improvement for clang. No Change for gcc.
=> intt optimization

src/pke/include/key/evalkey.h, src/pke/include/key/evalkeyrelin.h, src/pke/include/scheme/bfvrns/bfvrns-parametergeneration.h, src/pke/include/scheme/bgvrns/bgvrns-parametergeneration.h, src/pke/include/scheme/ckksrns/ckksrns-parametergeneration.h, src/pke/include/schemebase/base-leveledshe.h, src/pke/include/schemebase/base-parametergeneration.h, src/pke/include/schemebase/base-scheme.h, src/pke/include/schemerns/rns-parametergeneration.h, src/pke/lib/scheme/bfvrns/bfvrns-parametergeneration.cpp, src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp, src/pke/lib/scheme/ckksrns/ckksrns-parametergeneration.cpp, src/pke/lib/schemebase/base-leveledshe.cpp
* Replaced the DCRTPoly type with Element in template functions
* Made ParamsGenBGVRNS(), ParamsGenCKKSRNS() and ParamsGenBFVRNS() non-virtual in base-scheme.h
=> PKE class clean-up

src/core/include/lattice/hal/default/ildcrtparams.h, src/core/include/lattice/hal/default/ilparams.h, src/pke/include/encoding/ckkspackedencoding.h, src/pke/include/encoding/coefpackedencoding.h, src/pke/include/encoding/encodingparams.h, src/pke/include/encoding/packedencoding.h, src/pke/include/encoding/plaintext.h, src/pke/include/encoding/stringencoding.h, src/pke/include/metadata.h, src/pke/include/schemebase/base-cryptoparameters.h, src/pke/include/schemebase/rlwe-cryptoparameters.h, src/pke/include/schemerns/rns-cryptoparameters.h, src/pke/unittest/utils/UnitTestMetadataTest.h
- Corrected operator== for the family of cryptoparameters classes
- Fixed syntax for multiple virtual functions and virtual destructors
- Made some print functions protected to force users to use operator<<()
- Fixed multiple various issues, etc.
=> Corrected operator== for the family of cryptoparameters classes

src/pke/lib/scheme/gen-cryptocontext-params-validation.cpp
Validate digitSize for BFV/BGV:
it should not be greater than (MAX_MODULUS_SIZE/2) if keySwitchTechnique is set to "BV"
=> Added a validation for the cryptocontext params: digitSize should be less than 32 if keySwitchTechnique == BV (BGV/BFV)

src/core/lib/math/nbtheory2.cpp
1. Changed the type of **g0 and g from int32_t to uint64_t**:
- to prevent integer overflow if the result of (g*g0) is too high
- NativeInteger().ModInverse() always returns positive number, so the type can be unsigned
2. Replaced "if (i == int32_t(m - 1))" with "if (i == (static_cast<int32_t>(m) - 1))" as the subtraction should be performed on int32_t to avoid unexpected behavior. 
3. Replaced the C-style cast with the C++ one
=> Prevent integer overflow in FindAutomorphismIndex2nComplex()

src/core/include/math/chebyshev.h, src/core/lib/math/chebyshev.cpp, src/pke/examples/function-evaluation.cpp
Added a few lines to the documentation of EvalChebyshevCoefficients, and also added a function EvalChebyshevFunctionPtxt that computes the same thing as CryptoContext->EvalChebyshevFunction but on cleartext vector
=> Cleartext chebyshev

src/core/include/lattice/hal/default/ildcrtparams.h
dynamic_cast didn't work. only after removing "final" from ILDCRTParams, dynamic_cast started working.
this suggests that clang handles "final" differently in templates. most likely, it optimizes some things more aggressively, which affects RTTI and base class behavior (especially in templates).
NOTE: the test fails with the -O3 optimization flag, but passes with -O0 or when linked in Debug mode
=> Fixed failures in openfhe-python tests linked with clang++-18

src/pke/include/scheme/bfvrns/bfvrns-cryptoparameters.h, src/pke/include/scheme/bfvrns/gen-cryptocontext-bfvrns-internal.h, src/pke/include/scheme/bgvrns/bgvrns-cryptoparameters.h, src/pke/include/scheme/bgvrns/bgvrns-leveledshe.h, src/pke/include/scheme/bgvrns/gen-cryptocontext-bgvrns-internal.h, src/pke/include/scheme/ckksrns/ckksrns-cryptoparameters.h, src/pke/include/scheme/ckksrns/ckksrns-leveledshe.h, src/pke/include/scheme/ckksrns/gen-cryptocontext-ckksrns-internal.h, src/pke/include/schemebase/base-cryptoparameters.h, src/pke/include/schemebase/base-leveledshe.h, src/pke/include/schemebase/rlwe-cryptoparameters.h, src/pke/include/schemerns/rns-cryptoparameters.h, src/pke/lib/scheme/bgvrns/bgvrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/lib/schemerns/rns-leveledshe.cpp
Adds to the following parameters to `CryptoParametersRLWE` so that they could be accessed through the Crypto Context.
```
double m_noiseEstimate{0};
uint32_t m_multiplicativeDepth{1};
uint32_t m_evalAddCount{0};
uint32_t m_keySwitchCount{0};
uint32_t m_PRENumHops{0};
```
=> Add missing CCParams values to cryptocontext

src/pke/include/ciphertext.h, src/pke/lib/keyswitch/keyswitch-hybrid.cpp, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/lib/schemebase/base-leveledshe.cpp, src/pke/lib/schemebase/base-multiparty.cpp, src/pke/lib/schemerns/rns-multiparty.cpp
Cleanup of ciphertext.h
- proper implementation of constructors and assignment operators
- rename encodingType to m_encodingType to match convention of other data members
- reordering of data members for better alignment
- more efficient implementation of operator==
- more efficient return type for various member functions
- formatting
Replace ciphertext::CloneZero() with ciphertext::CloneEmpty()
- new implementation of CloneEmpty() that mimics CloneZero()
- removed CloneZero()
- proper use of new CloneEmpty() everywhere in repo that previously used CloneZero() or CloneEmpty()
- formatting
=> Replace CloneZero with CloneEmpty

src/pke/include/cryptocontext.h, src/pke/include/encoding/encodingparams.h, src/pke/include/encoding/plaintext.h, src/pke/lib/cryptocontext.cpp, src/pke/lib/encoding/stringencoding.cpp, src/pke/unittest/UnitTestSHE.cpp
- removed mutable from plaintext data members
- plaintext::SetFormat() no longer const
- ConstPlaintext& to Plaintext& for functions that use plaintext::SetFormat()
- added missing SetFormat(EVALUATION) within StringEncoding::Encode()
- formatting of touched files
- occurrences of const Plaintext to ConstPlaintext in appropriate signatures
- occurrences of const ConstPlaintext to ConstPlaintext in appropriate signatures
- occurrences of Plaintext/Ciphertext/PublicKey/PrivateKey to references in appropriate signatures
=> Remove need for mutable from plaintext.h

src/core/include/utils/memory.h, src/core/lib/math/discretegaussiangeneratorgeneric.cpp, src/core/lib/utils/demangle.cpp, src/core/lib/utils/get-call-stack.cpp, src/pke/include/scheme/ckksrns/gen-cryptocontext-ckksrns-internal.h
The Google-internal build of OpenFHE reports some missing inclues which are hard errors, and so adding these upstream allows us to reduce the amount of requried patches, which simplifies upgrading our version of OpenFHE. Also clang-tidy reported a few unused imports in these files.
=> Clean up some includes
