src/core/include/math/hal/intnat-hexl/transformnathexl-impl.h, src/core/lib/math/hal/intnat-hexl/benativehexl-math-impl.cpp, src/core/lib/math/hal/intnat-hexl/mubintvecnathexl.cpp
First round of HEXL mods.  This allows core and its unit tests to build successfully.
=> corrections to hexl code discovered 2022-03-15

README.md
I thought I had updated the URL but it looks like my system clipboard and CLion's clipboard didn't want to play nice
=> Copy-paste in previous didn't seem to work

docs/assets/sphinx_rsts/modules/pke.rst, docs/assets/sphinx_rsts/modules/pke/pke_keyswitch.rst, docs/assets/sphinx_rsts/modules/pke/pke_scheme.rst, src/binfhe/README.md, src/pke/README.md, src/pke/include/keyswitch/README.md, src/pke/include/keyswitch/keyswitch-base.h, src/pke/include/keyswitch/keyswitch-bv.h, src/pke/include/keyswitch/keyswitch-hybrid.h, src/pke/include/keyswitch/keyswitch-rns.h, src/pke/include/scheme/cryptocontextparams-base.h
=> Add documentation for PKE

src/pke/include/schemebase/base-cryptoparameters.h, src/pke/include/schemerns/rns-cryptoparameters.h, src/pke/lib/keyswitch/keyswitch-hybrid.cpp, src/pke/lib/schemebase/base-multiparty.cpp, src/pke/lib/schemebase/base-pke.cpp, src/pke/unittest/utbgvrns/UnitTestBGVrns.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
Added Hybrid KeySwitch used in PRE, for this changed public key generation in PKE and Multiparty
=> added hybrid pre

src/pke/unittest/UnitTestSHE.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
Fixes the following tests in UnitTestCKKSrns:
* EVAL_POLY
* RE_ENCRYPTION
* AUTO_LEVEL_REDUCE
Fixes KS_MOD_REDUCE_DCRT in UnitTestSHE
=> Fixed several unit tests

src/pke/include/constants.h, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-parametergeneration.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrns.cpp
* Fixes EvalMult by double for 128-bit CKKS
* Adds more unit tests for CKKS
=> fixed EvalMult by double for 128-bit CKKS

benchmark/src/bfv-mult-method-benchmark.cpp, benchmark/src/compare-bfv-hps-vs-behz.cpp, benchmark/src/compare-bfvrns-vs-bgvrns.cpp, src/pke/examples/depth-bgvrns.cpp, src/pke/include/scheme/cryptocontextparams-defaults.h, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/bfvrns/bfvrns-parametergeneration.cpp, src/pke/lib/schemebase/base-advancedshe.cpp, src/pke/unittest/utbfvrns/UnitTestBFVrnsCRTOperations.cpp
* Refines the noise estimates for BFV
* Changes the defaults for BGV, BFV, and CKKS
* FIxes EvalMultMany
Closes #81
=> Several fixes

src/binfhe/examples/eval-flooring.cpp
=> Fix a minor example issue due to parameter change

README.md, docs/index.rst, docs/sphinx_rsts/intro/get_started.rst, docs/sphinx_rsts/intro/security.rst, docs/sphinx_rsts/modules/core/lattice/core_lattice.rst, docs/sphinx_rsts/modules/core/lattice/hal.rst, docs/sphinx_rsts/modules/pke/pke.rst, src/README.md, src/binfhe/include/README.md, src/pke/include/README.md, src/pke/include/scheme/ckksrns/README.md
=> Address 127

src/pke/examples/advanced-real-numbers-128.cpp, src/pke/examples/advanced-real-numbers.cpp, src/pke/extras/ckks-bootstrap.cpp, src/pke/lib/cryptocontext.cpp, src/pke/lib/keyswitch/keyswitch-bv.cpp, src/pke/lib/keyswitch/keyswitch-hybrid.cpp, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/bfvrns/bfvrns-multiparty.cpp, src/pke/lib/scheme/bfvrns/bfvrns-parametergeneration.cpp, src/pke/lib/scheme/bfvrns/bfvrns-pke.cpp, src/pke/lib/scheme/bgvrns/bgvrns-leveledshe.cpp, src/pke/lib/scheme/bgvrns/bgvrns-multiparty.cpp, src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp, src/pke/lib/scheme/bgvrns/bgvrns-pke.cpp, src/pke/lib/scheme/ckksrns/ckksrns-advancedshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-multiparty.cpp, src/pke/lib/scheme/ckksrns/ckksrns-parametergeneration.cpp, src/pke/lib/schemebase/base-multiparty.cpp, src/pke/lib/schemebase/base-pke.cpp, src/pke/lib/schemerns/rns-leveledshe.cpp, src/pke/lib/schemerns/rns-multiparty.cpp, src/pke/lib/schemerns/rns-pke.cpp, src/pke/unittest/utbfvrns/UnitTestBFVrnsCRTOperations.cpp, src/pke/unittest/utbgvrns/UnitTestBGVrnsSerialize.cpp
…olymorphic classes in src/pke/
=> Replace static pointer cast with dynamic_pointer_cast

src/pke/include/cryptocontext.h, src/pke/include/scheme/bfvrns/bfvrns-parametergeneration.h, src/pke/include/scheme/bfvrns/bfvrns-pke.h, src/pke/include/schemebase/base-advancedshe.h, src/pke/include/schemebase/base-fhe.h, src/pke/include/schemebase/base-leveledshe.h, src/pke/include/schemebase/base-multiparty.h, src/pke/include/schemebase/base-pke.h, src/pke/include/schemebase/base-pre.h, src/pke/include/schemebase/base-scheme.h, src/pke/include/schemerns/rns-leveledshe.h, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/lib/schemerns/rns-leveledshe.cpp
=> Removal of default values for input parameters in virtual functions

src/core/include/utils/serial.h, src/core/include/utils/serializable.h, src/core/unittest/UnitTestXallocate.cpp
=> Compiler error fix for C++17 on macos

src/binfhe/unittest/UnitTestFunc.cpp, src/core/include/math/distributiongenerator.h, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp
All code changes have been tested on MinGW. Started 4 CI jobs.
closes #176
=> build errors and a crash on mingw

.gitmodules
=> Update the cereal code

src/pke/examples/advanced-real-numbers.cpp, src/pke/extras/ckks-bootstrap.cpp, src/pke/include/ciphertext.h, src/pke/include/cryptocontext.h, src/pke/include/encoding/ckkspackedencoding.h, src/pke/include/encoding/plaintext.h, src/pke/include/encoding/plaintextfactory.h, src/pke/include/scheme/ckksrns/ckksrns-fhe.h, src/pke/include/schemebase/base-cryptoparameters.h, src/pke/include/schemebase/rlwe-cryptoparameters.h, src/pke/lib/cryptocontext.cpp, src/pke/lib/encoding/ckkspackedencoding.cpp, src/pke/lib/encoding/coefpackedencoding.cpp, src/pke/lib/encoding/packedencoding.cpp, src/pke/lib/scheme/bfvrns/bfvrns-leveledshe.cpp, src/pke/lib/scheme/bfvrns/bfvrns-pke.cpp, src/pke/lib/scheme/bgvrns/bgvrns-leveledshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-advancedshe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp, src/pke/lib/schemebase/base-advancedshe.cpp, src/pke/lib/schemebase/base-leveledshe.cpp, src/pke/lib/schemebase/base-pke.cpp, src/pke/lib/schemerns/rns-leveledshe.cpp, src/pke/lib/schemerns/rns-multiparty.cpp, src/pke/lib/schemerns/rns-pke.cpp
=> Clean up the crypto parameters and ciphertext

src/pke/include/cryptocontext.h, src/pke/include/cryptocontextfactory.h, src/pke/include/encoding/coefpackedencoding.h, src/pke/include/encoding/plaintext.h, src/pke/include/encoding/plaintextfactory.h, src/pke/include/scheme/bfvrns/gen-cryptocontext-bfvrns-internal.h, src/pke/include/scheme/bgvrns/gen-cryptocontext-bgvrns-internal.h, src/pke/include/scheme/ckksrns/gen-cryptocontext-ckksrns-internal.h, src/pke/include/scheme/scheme-id.h, src/pke/lib/cryptocontextfactory.cpp, src/pke/lib/encoding/coefpackedencoding.cpp, src/pke/lib/schemebase/base-advancedshe.cpp, src/pke/lib/schemebase/base-multiparty.cpp
SchemeId should be enum, not std::string
=> Making schemeId enum

src/pke/include/cryptocontext.h, src/pke/include/encoding/encodingparams.h, src/pke/include/scheme/ckksrns/ckksrns-fhe.h, src/pke/include/schemebase/base-advancedshe.h, src/pke/include/schemebase/base-fhe.h, src/pke/include/schemebase/base-multiparty.h, src/pke/include/schemebase/base-pke.h, src/pke/include/schemebase/base-pre.h, src/pke/include/schemebase/base-scheme.h, src/pke/lib/cryptocontext.cpp, src/pke/lib/scheme/bfvrns/bfvrns-multiparty.cpp, src/pke/lib/scheme/bfvrns/bfvrns-pke.cpp, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp, src/pke/lib/schemebase/base-advancedshe.cpp, src/pke/lib/schemebase/base-leveledshe.cpp, src/pke/lib/schemebase/base-multiparty.cpp, src/pke/lib/schemebase/base-pke.cpp, src/pke/lib/schemebase/base-pre.cpp, src/pke/lib/schemebase/base-scheme.cpp, src/pke/lib/schemerns/rns-multiparty.cpp, src/pke/lib/schemerns/rns-pke.cpp
=> Normalizing includes of headers

src/core/include/lattice/hal/dcrtpoly-interface.h, src/core/include/lattice/hal/default/dcrtpoly.h, src/core/lib/lattice/hal/default/dcrtpoly.cpp, src/pke/lib/keyswitch/keyswitch-hybrid.cpp, src/pke/lib/scheme/ckksrns/ckksrns-leveledshe.cpp
=> Resolve issue #99 (different number of towers in multiplication in CKKS bootstrapping)

src/core/include/math/hal/intnat/ubintnat.h, src/pke/include/cryptocontext.h, src/pke/lib/cryptocontext.cpp
=> Building error in MacOs

src/pke/lib/scheme/cryptocontextparams-base-impl.cpp
=> Fixed a bug in SET_TO_SCHEME_DEFAULT

docs/README.md, docs/sphinx_rsts/misc/z_migration_guide.rst
1. The guide is "How To Migrate A User Project From Palisade To OpenFHE"
2. The changes will merge into dev and after that will go in to the main branch
3. No CI jobs will run for this PR as there are no code changes
=> Migration guide

src/core/include/math/hal/bigintfxd/backendfxd.h, test/Main_TestAll.cpp
Ayoooo as in title
Closes #286
=> Moved out MathBackend

src/pke/lib/scheme/bfvrns/bfvrns-parametergeneration.cpp, src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp, src/pke/lib/scheme/ckksrns/ckksrns-parametergeneration.cpp
fixes #298 
Added check for equality of batch size to a power of two
=> added check for batch size to be a power of two

src/binfhe/lib/lwe-pke.cpp
Fixed vectorization in pubkeygen for xor performance difference in ske vs pke
=> Fixed vectorization bug

src/pke/examples/FUNCTION_EVALUATION.md, src/pke/lib/scheme/ckksrns/ckksrns-utils.cpp
Changed logic of how to select the PS parameters given the degree of the polynomial that needs to be evaluated. In particular, for commonly used degrees (< 2205), hardcode parameters that minimize the multiplicative depth, and at that multiplicative depth, minimize the number of homomorphic multiplications. For larger degrees, a heuristic tries to approximate this logic.
=> PS parameters

src/core/lib/lattice/hal/default/dcrtpoly.cpp
Solving issue https://github.com/openfheorg/openfhe-development/issues/355
We should not drop elements of a DCRTPoly that has 1 or less elements.
=> fix issue 355 - should not delete elements of DCRTPoly with one element

src/pke/include/schemerns/rns-cryptoparameters.h, src/pke/lib/keyswitch/keyswitch-hybrid.cpp, src/pke/lib/schemerns/rns-cryptoparameters.cpp
Hybrid Key Switching optimization from https://eprint.iacr.org/2018/117, Section 3.3.
See also: https://eprint.iacr.org/2021/204, Appendix B.3 
Discussions are in: https://openfhe.discourse.group/t/keyswitch-keys-reuse-optimization-for-hybrid-key-switching/471/8
=> Hybrid Key Switching Optimization

src/pke/examples/inner-product.cpp, src/pke/unittest/utbfvrns/UnitTestBFVrnsInnerProduct.cpp, src/pke/unittest/utckksrns/UnitTestCKKSrnsInnerProduct.cpp
Add in `EvalInnerProduct` example and unittest
Closes #381
=> add in inner product example

src/pke/lib/scheme/bfvrns/bfvrns-parametergeneration.cpp, src/pke/unittest/UnitTestSHE.cpp
Fixes the bug described in https://github.com/openfheorg/openfhe-development/issues/382
=> Issue 382 - Fix BFV security check

CMakeLists.User.txt, docs/sphinx_rsts/intro/building_user_applications.rst, docs/sphinx_rsts/intro/installation/installation.rst
…tion and updated docs with other OSs where OpenFHE has been sucessfully linked
=> Add instructions for custom build location in user project

README.md, docs/static_docs/Best_Performance.md
* added best performance guidelines
* Update Best_Performance.md
* Update Best_Performance.md
* Update README.md
* Update Best_Performance.md
* Update Best_Performance.md
* Update Best_Performance.md
* Update Best_Performance.md
---------
=> Added guidelines for best performance build configuration (#556)

src/core/include/math/nbtheory-impl.h, src/core/include/math/nbtheory.h, src/core/lib/math/hal/bigintdyn/be4-math-impl.cpp, src/core/lib/math/hal/bigintfxd/be2-math-impl.cpp, src/core/lib/math/hal/bigintntl/be6-math-impl.cpp, src/core/lib/math/hal/intnat/benative-math-impl.cpp, src/pke/unittest/utbgvrns/UnitTestBGVrns.cpp, src/pke/unittest/utbgvrns/UnitTestBGVrnsSerialize.cpp
Fixes the bug affecting BGV FIXEDMANUAL and FIXEDAUTO modes
=> fixed a bug with First/Last/Next/PreviousPrime

src/pke/lib/schemerns/rns-cryptoparameters.cpp
Small fix for hybrid key switching parameterization in BFV
=> added special handling for BFV parameterization

src/pke/lib/encoding/coefpackedencoding.cpp, src/pke/lib/encoding/packedencoding.cpp, src/pke/lib/encoding/stringencoding.cpp
Cleans noise during decoding for
- PackedEncoding
- CoefPackedEncoding
- StringEncoding
=> Clean noise during decoding

src/binfhe/include/binfhe-constants.h, src/binfhe/include/binfhecontext.h, src/binfhe/lib/binfhe-constants-impl.cpp, src/binfhe/lib/binfhecontext.cpp
Adds isMethodCompatible(), which checks if Specified BINFHE_METHOD and BINFHE_PARAMSET are compatible within GenerateBinFHEContext()
=> Check if Specified BINFHE_METHOD and BINFHE_PARAMSET are compatible within GenerateBinFHEContext()

src/pke/include/scheme/ckksrns/ckksrns-fhe.h, src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp
Minor fixes in the CKKS bootstrapping implementation for composite scaling
=> 910 small bootstrapping changes

src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp
Revert the change introduced during commit f7900119df537009c89e81e1a0e38c591db5b28b
=> fixes the bug with CKKS bootstrapping for N=2^17
